#!/usr/bin/env python3
"""Single-source branding generator (placeholder phase).

SPDX-License-Identifier: GPL-3.0-only

The hand-drawn launcher glyph lives in exactly one place:

    data/icons/hicolor/scalable/apps/top.vikasmi.Prelude.svg

Everything else branding-shaped is derived from it and must never be
hand-edited:

* data/icons/hicolor/symbolic/apps/top.vikasmi.Prelude-symbolic.svg
  (monochrome 16px, same geometry scaled down)
* android/data/ic_launcher_foreground.xml
  (white glyph on the single brand blue for the adaptive icon)

Pixiewood `src://` includes can only reference the source tree, so the
derivatives stay checked in; `check` (used in CI) fails on drift.
Package-time rasters (AppImage PNG, macOS icns, Windows ICO) are
rendered from the same source SVG in CI, never committed.

Usage:
    python3 branding/generate.py check        # derivatives + icon refs
    python3 branding/generate.py write        # rewrite derivatives
    python3 branding/generate.py check-icons  # blp/rs refs vs bundle
    python3 branding/generate.py png-to-ico a.png b.png -o out.ico
"""

from __future__ import annotations

import argparse
import re
import struct
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "data/icons/hicolor/scalable/apps/top.vikasmi.Prelude.svg"
SYMBOLIC = REPO / (
    "data/icons/hicolor/symbolic/apps/top.vikasmi.Prelude-symbolic.svg"
)
AVD = REPO / "android/data/ic_launcher_foreground.xml"
GRESOURCE = REPO / "src/prelude.gresource.xml"

BRAND_BLUE = "#3584e4"
INK = "#2e3436"
GLYPH_WHITE = "#ffffff"

SVG_NS = "http://www.w3.org/2000/svg"
ANDROID_NS = "http://schemas.android.com/apk/res/android"

NUMBER_RE = re.compile(r"-?\d+(?:\.\d+)?")


def n(value: float) -> str:
    """Stable short number formatting shared by all emitters."""
    return "%g" % round(value, 2)


def scale_numbers(text: str, factor: float) -> str:
    return NUMBER_RE.sub(lambda m: n(float(m.group(0)) * factor), text)


def read_source() -> tuple[str, ET.Element, ET.Element, ET.Element]:
    """Return (background fill, circle, stem rect, flag path) of the glyph."""
    root = ET.parse(SOURCE).getroot()
    ns = {"s": SVG_NS}

    def find(tag: str) -> ET.Element:
        el = root.find(f"s:{tag}", ns)
        if el is None:
            raise SystemExit(f"branding: source SVG lost its <{tag}> element")
        return el

    bg = find("rect")
    circle = find("circle")
    shapes = root.findall("s:rect", ns)
    paths = root.findall("s:path", ns)
    if len(shapes) != 2 or len(paths) != 1:
        raise SystemExit(
            "branding: source SVG shape changed "
            "(expected bg rect + stem rect + 1 flag path); "
            "teach generate.py the new geometry first"
        )
    # Document order: background rect first, stem rect second.
    stem = shapes[1]
    if bg.get("fill") != BRAND_BLUE:
        raise SystemExit("branding: source background is no longer brand blue")
    for el in (circle, stem, paths[0]):
        if el.get("fill") != GLYPH_WHITE:
            raise SystemExit("branding: source glyph is no longer white")
    return bg.get("fill", BRAND_BLUE), circle, stem, paths[0]


def render_symbolic(
    circle: ET.Element, stem: ET.Element, flag: ET.Element
) -> str:
    f = 16 / 64
    lines = [
        '<?xml version="1.0"?>',
        "<!-- TEMP PLACEHOLDER. Single source: "
        "data/icons/hicolor/scalable/apps/top.vikasmi.Prelude.svg. -->",
        "<!-- Generated by branding/generate.py; do not hand-edit. -->",
        '<svg xmlns="http://www.w3.org/2000/svg" '
        'width="16" height="16" viewBox="0 0 16 16">',
        f'  <circle cx="{n(float(circle.get("cx", "0")) * f)}" '
        f'cy="{n(float(circle.get("cy", "0")) * f)}" '
        f'r="{n(float(circle.get("r", "0")) * f)}" fill="{INK}"/>',
        f'  <rect x="{n(float(stem.get("x", "0")) * f)}" '
        f'y="{n(float(stem.get("y", "0")) * f)}" '
        f'width="{n(float(stem.get("width", "0")) * f)}" '
        f'height="{n(float(stem.get("height", "0")) * f)}" fill="{INK}"/>',
        f'  <path d="{scale_numbers(flag.get("d", ""), f)}" fill="{INK}"/>',
        "</svg>",
        "",
    ]
    return "\n".join(lines)


def render_avd(
    circle: ET.Element, stem: ET.Element, flag: ET.Element
) -> str:
    f = 108 / 64
    cx = float(circle.get("cx", "0")) * f
    cy = float(circle.get("cy", "0")) * f
    r = float(circle.get("r", "0")) * f
    sx = float(stem.get("x", "0")) * f
    sy = float(stem.get("y", "0")) * f
    sw = float(stem.get("width", "0")) * f
    sh = float(stem.get("height", "0")) * f
    ellipse = (
        f"M{n(cx - r)},{n(cy)}"
        f"a{n(r)},{n(r)} 0 1,0 {n(2 * r)},0"
        f"a{n(r)},{n(r)} 0 1,0 -{n(2 * r)},0"
    )
    stem_path = f"M{n(sx)},{n(sy)}h{n(sw)}v{n(sh)}h-{n(sw)}Z"
    a = ANDROID_NS
    lines = [
        '<?xml version="1.0"?>',
        "<!-- TEMP PLACEHOLDER. Single source: "
        "data/icons/hicolor/scalable/apps/top.vikasmi.Prelude.svg. -->",
        "<!-- Generated by branding/generate.py; do not hand-edit. -->",
        "<!-- SPDX-License-Identifier: GPL-3.0-only -->",
        f'<vector xmlns:android="{a}" '
        'android:width="108dp" android:height="108dp" '
        'android:viewportWidth="108" android:viewportHeight="108">',
        f'  <path android:fillColor="#FFFFFF" android:pathData="{ellipse}"/>',
        f'  <path android:fillColor="#FFFFFF" '
        f'android:pathData="{stem_path}"/>',
        '  <path android:fillColor="#FFFFFF" '
        f'android:pathData="{scale_numbers(flag.get("d", ""), f)}"/>',
        "</vector>",
        "",
    ]
    return "\n".join(lines)


def check_icons() -> int:
    """Every icon-name used in UI/code must be in the GResource bundle."""
    refs: set[str] = set()
    for blp in sorted((REPO / "ui").glob("*.blp")):
        refs.update(
            re.findall(r'icon-name:\s*"([^"]+)"', blp.read_text())
        )
    for rs in sorted((REPO / "src").glob("*.rs")):
        refs.update(re.findall(r'"([A-Za-z0-9_-]*symbolic)"', rs.read_text()))
    root = ET.parse(GRESOURCE).getroot()
    bundled = {
        Path(f.text or "").stem
        for f in root.iter("file")
        if (f.text or "").startswith("icons/")
    }
    missing = sorted(refs - bundled)
    stale = sorted(bundled - refs)
    for name in stale:
        print(f"branding: note: bundled but unreferenced: {name}")
    if missing:
        print("branding: icons referenced but NOT bundled:")
        for name in missing:
            print(f"  missing: {name}")
        return 1
    print(f"branding: icon refs OK ({len(refs)} referenced, all bundled)")
    return 0


def cmd_check() -> int:
    _, circle, stem, flag = read_source()
    problems = []
    if SYMBOLIC.read_text() != render_symbolic(circle, stem, flag):
        problems.append(f"{SYMBOLIC.relative_to(REPO)} drifts from source")
    if AVD.read_text() != render_avd(circle, stem, flag):
        problems.append(f"{AVD.relative_to(REPO)} drifts from source")
    for p in problems:
        print(f"branding: {p} (run branding/generate.py write)")
    rc = 1 if problems else 0
    if rc == 0:
        print("branding: derivatives OK (symbolic + AVD match source)")
    return check_icons() or rc


def cmd_write() -> int:
    _, circle, stem, flag = read_source()
    SYMBOLIC.write_text(render_symbolic(circle, stem, flag))
    AVD.write_text(render_avd(circle, stem, flag))
    print("branding: rewrote symbolic SVG + Android foreground AVD")
    return check_icons()


def png_size(path: Path) -> tuple[int, int]:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"branding: not a PNG: {path}")
    (w, h) = struct.unpack(">II", data[16:24])
    if w > 256 or h > 256 or w != h:
        raise SystemExit(f"branding: ICO needs square PNGs <=256px: {path}")
    return w, h


def cmd_png_to_ico(pngs: list[Path], out: Path) -> int:
    """Assemble an ICO from square PNGs (PNG-compressed entries, Vista+)."""
    items = sorted(
        ((png_size(p), p, p.read_bytes()) for p in pngs),
        key=lambda t: t[0],
    )
    count = len(items)
    header = struct.pack("<HHH", 0, 1, count)
    entries = b""
    offset = 6 + 16 * count
    for (w, _), _, data in items:
        entries += struct.pack(
            "<BBBBHHII", w if w < 256 else 0, w if w < 256 else 0,
            0, 0, 1, 32, len(data), offset,
        )
        offset += len(data)
    out.write_bytes(header + entries + b"".join(d for _, _, d in items))
    print(f"branding: wrote {out.relative_to(REPO)} ({count} sizes)")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Prelude branding helper")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check", help="verify derivatives + icon refs")
    sub.add_parser("write", help="rewrite derivatives from source")
    sub.add_parser("check-icons", help="verify icon refs vs bundle")
    ico = sub.add_parser("png-to-ico", help="assemble ICO from PNGs")
    ico.add_argument("pngs", nargs="+", type=Path)
    ico.add_argument("-o", "--output", required=True, type=Path)
    args = parser.parse_args(argv)
    if args.cmd == "check":
        return cmd_check()
    if args.cmd == "write":
        return cmd_write()
    if args.cmd == "check-icons":
        return check_icons()
    if args.cmd == "png-to-ico":
        return cmd_png_to_ico(args.pngs, args.output)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
